"""
This script is used to train the data generated by single fidelity mesh
We train L1, L2, L3 mesh training set here. The trainset is analyzed by ADFlow 

NN models changes with different outputs and different fidelity of data

"""

import tensorflow as tf
import numpy as np
import datetime
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Conv2D,LeakyReLU,Dropout,Flatten
from tensorflow.keras import activations
import tensorflow as tf
from tensorflow import keras
from keras import backend as K
from tensorflow.keras import layers
import os
from tensorflow.keras.models import load_model,save_model

class PrintDot(keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs):
    if epoch % 100 == 0: print('')
    print('.', end='')

def norm_coeff(old_coeff, min_coeff, max_coeff):
    return 2.0 * ((old_coeff - min_coeff)/(max_coeff-min_coeff) - 0.5)

def denorm_coeff(new_coeff, min_coeff, max_coeff):
    return (new_coeff + 1.0) * 0.5 * (max_coeff - min_coeff) + min_coeff

class Neural_Network(object):
    def __init__(self, input_norm, target_norm, name_save):

        self.name = name_save

        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(input_norm, target_norm, test_size=0.2, random_state=10)

        self.X_train, self.X_val, self.y_train, self.y_val = train_test_split(self.X_train, self.y_train, test_size=0.2, random_state=10)

        self.X_train, self.y_train = shuffle(self.X_train, self.y_train)
        self.X_val, self.y_val = shuffle(self.X_val, self.y_val)

        self.model = tf.keras.Sequential()
        self.model.add(tf.keras.layers.Dense(100, activation='tanh', input_shape=(self.X_train.shape[1],)))
        self.model.add(tf.keras.layers.Dense(100, activation='tanh'))
        self.model.add(tf.keras.layers.Dense(100, activation='tanh'))
        self.model.add(tf.keras.layers.Dense(100, activation='tanh'))
        self.model.add(tf.keras.layers.Dense(100, activation='tanh'))
        self.model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

        self.model.compile(optimizer=tf.keras.optimizers.Adam(
                                        learning_rate=0.0001,
                                        beta_1=0.9,
                                        beta_2=0.999,
                                        epsilon=1e-07,
                                        amsgrad=False,
                                        weight_decay=None,
                                        clipnorm=None,
                                        clipvalue=None,
                                        global_clipnorm=None,
                                        use_ema=False,
                                        ema_momentum=0.99,
                                        ema_overwrite_frequency=None,
                                        jit_compile=True,
                                        name='Adam',
                                    ),
                  loss='mae',
                  metrics=['mae', 'mse'])

        tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir='./logs/data_{}'.format(datetime.datetime.now().strftime("%Y%m%d-%H%M%S")), update_freq=1)
        self.history = self.model.fit(self.X_train, self.y_train,
                validation_data=(self.X_val, self.y_val),
                epochs=500, batch_size= 256,
                callbacks=[PrintDot(),tensorboard_callback])

        self.model.save('./models/Model_{}.h5'.format(self.name))


    def evaluate_model(self):

        loss, mae, mse = self.model.evaluate(self.X_test, self.y_test, verbose=2)
        print("./plots/Testing set Mean Abs Error: {:5.2f} MPG".format(mae))

    def plot_history(self):
        history = self.history
        hist = pd.DataFrame(history.history)
        hist['epoch'] = history.epoch

        plt.figure()
        plt.xlabel('Epoch')
        plt.ylabel('Mean Abs Error [MPG]')
        plt.plot(hist['epoch'], hist['mae'],
                label='Train Error')
        plt.plot(hist['epoch'], hist['val_mae'],
                label = 'Val Error')
        #   plt.ylim([0,5])
        plt.legend()
        plt.savefig('./plots/Mean Abs Error [MPG]_{}.png'.format(self.name))

        plt.figure()
        plt.xlabel('Epoch')
        plt.ylabel('Mean Square Error [$MPG^2$]')
        plt.plot(hist['epoch'], hist['mse'],
                label='Train Error')
        plt.plot(hist['epoch'], hist['val_mse'],
                label = 'Val Error')
        #   plt.ylim([0,20])
        plt.legend()
        plt.savefig('./plots/Mean Square Error [$MPG^2$]_{}.png'.format(self.name))

def load_predict(model_path, norm_data, bounds):

    model_para = load_model(model_path)
    predict_para = model_para.predict(norm_data)
    denorm_para = denorm_coeff(predict_para, bounds[0], bounds[1])
    return denorm_para

def error_percentage(CFD_data, predict_data):

    # CFD_cl = validatedata[:, 60].flatten()
    # predict_cl = denorm_cl.flatten()
    error = np.absolute(CFD_data - predict_data)
    percentage = np.linalg.norm(error) / np.linalg.norm(CFD_data) * 100.0
    return error, percentage

if __name__ == '__main__':

    bounds = np.loadtxt("/home/aobo/MACH-Aero/input/bounds.txt")

    L3_bounds = np.array(
        [
            [0.15, 0.72],
            [0.013, 0.053],
            [-0.3, -0.03],
        ]
    )

    L2_input = np.loadtxt('L2_training.txt')

    L2_input = np.unique(L2_input,axis=0)

    L2_CFD_bounds = np.array(
        [
            [np.min(L2_input[:, 60]), np.max(L2_input[:, 60])],
            [np.min(L2_input[:, 61]), np.max(L2_input[:, 61])],
            [np.min(L2_input[:, 62]), np.max(L2_input[:, 62])],
        ]
    )

    L2_bounds = np.concatenate((bounds, L2_CFD_bounds), axis=0)
    L3_bounds = np.concatenate((bounds, L3_bounds), axis=0)


    norm_L2_input = norm_coeff(L2_input, L3_bounds.T[0,:], L3_bounds.T[1,:])

    CL_LF_model = load_model("/home/aobo/MACH-Aero/input/model_cl.h5")

    CL_LF_predict_norm = CL_LF_model.predict(norm_L2_input[:, :60])

    CL_LF_predict = denorm_coeff(CL_LF_predict_norm, L3_bounds.T[0,60], L3_bounds.T[1,60])

    X_LF_HF = np.concatenate((norm_L2_input, ))


    dict = {
        "CL_L2":L2_input[:, 60].flatten(),
        "CL_L3_predict":CL_LF_predict.flatten(),
        "residual":L2_input[:, 60].flatten() - CL_LF_predict.flatten(),
    }
    data = pd.DataFrame(dict)
    data.to_csv("compare.csv")

    X = np.concatenate((norm_L2_input[:, :60], CL_LF_predict_norm), axis=1)

    y = norm_coeff(L2_input[:, 60], L2_CFD_bounds[0, 0], L2_CFD_bounds[0, 1])

    model = Neural_Network(X, y,"CL_MFNN")
    model.evaluate_model()
    model.plot_history()

    L2_validate = L2_input[:, -1000:]

    norm_L2_validate = norm_coeff(L2_validate, L2_bounds.T[0,:], L2_bounds.T[1,:])


    denorm_cl = load_predict("/home/aobo/MACH-Aero/MF_data_driven_NN/NN_training/models/Model_CL_MFNN.h5", X, L2_CFD_bounds[0,:])
    # denorm_cd = load_predict("Model_Operational_based_CD.h5", norm_validate_data[:, :60], operation_bounds.T[:,61])
    # denorm_cm = load_predict("Model_Operational_based_CM.h5", norm_validate_data[:, :60], operation_bounds.T[:,62]) 

    # model_cl = load_model("Model_Operational_based_CL.h5")
    # predict_cl = model_cl.predict(norm_validate_data[:, :60])
    # denorm_cl = denorm_coeff(predict_cl,operation_bounds.T[0,60],operation_bounds.T[1,60])


    CFD_cl = L2_validate[:, 60].flatten()
    predict_cl = denorm_cl.flatten()
    # CFD_cd = validatedata[:, 61].flatten()
    # predict_cd = denorm_cd.flatten()
    # CFD_cm = validatedata[:, 62].flatten()
    # predict_cm = denorm_cm.flatten()

    error_cl, per_cl = error_percentage(CFD_cl, predict_cl)
    # error_cd, per_cd = error_percentage(CFD_cd, predict_cd)
    # error_cm, per_cm = error_percentage(CFD_cm, predict_cm)


    dict_error = {
        "CL":CFD_cl,
        "Predict_CL":predict_cl,
        "Error_CL":error_cl,
        # "CD":CFD_cd,
        # "Predict_CD":predict_cd,
        # "Error_CD":error_cd,
        # "CM":CFD_cm,
        # "Predict_CM":predict_cm,
        # "Error_CM":error_cm,
    }
    data_error = pd.DataFrame(dict_error)
    data_error.to_csv("error_NN_CL.csv")

    f = open('percetage.txt','a')
    f.write('%.5f\n%.5f\n%.5f\n'%(per_cl, 0, 0))
    # f.write('%.5f\n%.5f\n%.5f\n'%(per_cl, per_cd, per_cm))
    f.close()